language: objective-c
osx_image: xcode9.2

branches:
  only:
  - master

script:
- qmake mpc-qt.pro
- make -j2
- make install
- macdeployqt mpc-qt.app -libpath=/usr/local/lib/
- python macdeployqtfix/macdeployqtfix.py mpc-qt.app/Contents/MacOS/mpc-qt /usr/local/Cellar/qt/5.11.2/ -v

before_install:
- brew update
- cd $(brew --repo homebrew/core)
- git checkout 5eb54ced793999e3dd3bce7c64c34e7ffe65ddfd
- cd $TRAVIS_BUILD_DIR
- brew install mpv
- brew install qt
- brew link qt --force
- brew install librsvg

install:
- git clone --branch v0.29.1 https://github.com/mpv-player/mpv.git
- cp mpv/libmpv/* /usr/local/Cellar/mpv/0.29.1_1/include/mpv/
- rm -rf mpv
- git clone https://github.com/arl/macdeployqtfix.git
- git fetch --unshallow

before_deploy:
- ls -al
- brew upgrade python
- pip install dmgbuild
- dmgbuild -s make-release-mac.py "mpc-qt" mpc-qt.dmg

deploy:
  skip_cleanup: true
  on: master
  provider: bintray
  file: "bintray.json"
  user: alby128
  key:
    secure: "h1ZKUCkLilR6NDlrF73g1GHFFVCN2F8dDBnJNwiYaUPZT4znToZwZE8Qh2ukLaz2jjIr2d6fxN+jV1TLJPjq5v7HRsXEJZjy64Fp0OniO3SGpzEvnQZL+58RUwmQU0Y+VeBbDLmyu5wNrLbmXZnjeK1OcJYM1CV6qxHP+uQA5QCxkCqa4/MP5/rmpTRNu/iz0zQD1qSrqf0q61xCG+aJCnX6JhQvs4w1UXdU4Qy53OfAeI1kDq7Fwpoa+AxOMfXvnIy9Yo0igdi64s8e8klv+uaqJ/TvslFDslqbivNOZuXv1+wZCq+ac4npPtDMQZyWoBvMZ0U24LJ3e24en2OsRcQBXdaiTS1r4PAstVn7VjFWgbgzgGTBSKlqucGgxg0O3RsX+GiG1yHjsIJ9JF9AtBn9Awcy5NMJsOi9meLN+AgEOVtMIEVWDH8m5jMK+aCHYsm7tEBYcjFpTaYl3/t9EaPeqjKpOvUNSJDTfSnsuIXKp233GIiIDWbMXzLWCR8F1Ijk9FNTJqtJECpBpZOUiHkPN95NPxz98w0CW6rDYjJmZImNYpgflSQ4gzH2w3bfqgvJJqbrsa1imZqMzH+JrmlUFfmZAwNfPJOrKJbSUsZisH8CNvL4x4wHt7iOhZSsT6nO8idkDP0ukKpXJ0qbKluU2Fqfvl1nNIxRYFFkyQs="
